/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JPasswordField;
import javax.swing.JTextField;



/**
 *
 * @author Ananthakrishnan H
 */
public class SystemAdminLogin extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminLogin
     */
    public SystemAdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        SystemAdminLoginHeading = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SystemAdminLoginUsernameLabel = new javax.swing.JLabel();
        SystemAdminLoginPasswordLabel = new javax.swing.JLabel();
        SystemAdminLoginUsernameTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        SystemAdminLoginPasswordField = new javax.swing.JPasswordField();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        SystemAdminLoginHeading.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SystemAdminLoginHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SystemAdminLoginHeading.setText("System Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SystemAdminLoginHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SystemAdminLoginHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jSplitPane1.setTopComponent(jPanel1);

        SystemAdminLoginUsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SystemAdminLoginUsernameLabel.setText("Username");

        SystemAdminLoginPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SystemAdminLoginPasswordLabel.setText("Password");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        SystemAdminLoginPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemAdminLoginPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SystemAdminLoginPasswordLabel)
                    .addComponent(SystemAdminLoginUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(SystemAdminLoginUsernameTextField)
                    .addComponent(SystemAdminLoginPasswordField))
                .addContainerGap(379, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {SystemAdminLoginPasswordLabel, SystemAdminLoginUsernameLabel});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SystemAdminLoginUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SystemAdminLoginUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SystemAdminLoginPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SystemAdminLoginPasswordField))
                .addGap(73, 73, 73)
                .addComponent(submitButton)
                .addContainerGap(516, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {SystemAdminLoginPasswordLabel, SystemAdminLoginUsernameLabel});

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        SystemAdminHome systemAdmin = new SystemAdminHome();
        
        String x = SystemAdminLoginUsernameTextField.getText();
        char [] Chars = new char[30];
        Chars = SystemAdminLoginPasswordField.getPassword();
        String y;
        y = new String(Chars);
        if(x.equals("sysadmin") && y.equals("password")){
            jSplitPane1.setBottomComponent(systemAdmin);
        }
        
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void SystemAdminLoginPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemAdminLoginPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SystemAdminLoginPasswordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SystemAdminLoginHeading;
    private javax.swing.JPasswordField SystemAdminLoginPasswordField;
    private javax.swing.JLabel SystemAdminLoginPasswordLabel;
    private javax.swing.JLabel SystemAdminLoginUsernameLabel;
    private javax.swing.JTextField SystemAdminLoginUsernameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
