/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JFrame;

/**
 *
 * @author Ananthakrishnan H
 */
public class SystemAdminHome extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdmin
     */
    JFrame frame;
    public SystemAdminHome() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PersonButton = new javax.swing.JButton();

        PersonButton.setText("Person");
        PersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(PersonButton)
                .addContainerGap(539, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(PersonButton)
                .addContainerGap(844, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonButtonActionPerformed
        // TODO add your handling code here:
        SystemAdminPersonScreen systemAdminPersonScreen = new SystemAdminPersonScreen();
        frame = new JFrame("SystemAdminPerson");
        frame.add(systemAdminPersonScreen);
        frame.show();
    }//GEN-LAST:event_PersonButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PersonButton;
    // End of variables declaration//GEN-END:variables
}
