/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author Ananthakrishnan H
 */
public class SystemAdminHome extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdmin
     */
    JFrame frame;
    public SystemAdminHome() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PersonButton = new javax.swing.JButton();
        PatientButton = new javax.swing.JButton();
        DoctorButton = new javax.swing.JButton();
        HospitalButton = new javax.swing.JButton();
        EncountersButton = new javax.swing.JButton();

        PersonButton.setText("Person");
        PersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonButtonActionPerformed(evt);
            }
        });

        PatientButton.setText("Patient");
        PatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientButtonActionPerformed(evt);
            }
        });

        DoctorButton.setText("Doctor");
        DoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorButtonActionPerformed(evt);
            }
        });

        HospitalButton.setText("Hospital");
        HospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalButtonActionPerformed(evt);
            }
        });

        EncountersButton.setText("Encounters");
        EncountersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncountersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PersonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DoctorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HospitalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(EncountersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(511, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(PersonButton)
                .addGap(18, 18, 18)
                .addComponent(PatientButton)
                .addGap(18, 18, 18)
                .addComponent(DoctorButton)
                .addGap(18, 18, 18)
                .addComponent(HospitalButton)
                .addGap(18, 18, 18)
                .addComponent(EncountersButton)
                .addContainerGap(680, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonButtonActionPerformed
        // TODO add your handling code here:
        SystemAdminPersonScreen systemAdminPersonScreen = new SystemAdminPersonScreen();
        frame = new JFrame("SystemAdminPerson");
        frame.add(systemAdminPersonScreen);
        frame.setMinimumSize(new Dimension(1000,1000));
        frame.show();
    }//GEN-LAST:event_PersonButtonActionPerformed

    private void PatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientButtonActionPerformed

    private void DoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorButtonActionPerformed

    private void HospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalButtonActionPerformed

    private void EncountersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncountersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EncountersButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoctorButton;
    private javax.swing.JButton EncountersButton;
    private javax.swing.JButton HospitalButton;
    private javax.swing.JButton PatientButton;
    private javax.swing.JButton PersonButton;
    // End of variables declaration//GEN-END:variables
}
